---
# These user/group combinations definitely DO exist on pulp server

# Will fail before we get here if the group/user doesn't exist
- name: Remove user from group
  # DELETE {{ pulp_url }}/pulp/api/v3/groups/880/users/11/
  uri:
    url: "{{ pulp_url }}{{ user_group.pulp_href }}users/{{ exist_users[user_index].id }}/"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    method: DELETE
    # Always returns 204 even if user/group doesn't exist
    status_code: 204
    force_basic_auth: true
  # If we get here, we're always changing something
  changed_when: true
  loop: "{{ exist_users[user_index].existing_groups | selectattr('name', 'equalto', remove_group) }}"
  loop_control:
    loop_var: user_group
    label: "{{ exist_users[user_index].username }} {{ user_group.name }}"
