---
- name: Get information for each user
  uri:
    url: "{{ pulp_user_url }}?username={{ item.username }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    method: GET
    status_code: 200
    force_basic_auth: true
  loop: "{{ pulp_users }}"
  register: users_get_result

- name: Reset users facts
  set_fact:
    remove_users: []
    create_users: []
    update_users: []

- name: Set users to delete fact
  set_fact:
    remove_users: "{{ remove_users + [user.json.results[0]] }}"
  loop: "{{ users_get_result.results }}"
  loop_control:
    loop_var: "user"
    label: "{{ user.item.username }}"
  when:
    - user.json.count == 1
    - user.item.state is defined
    - user.item.state == "absent"

- name: Set users to create fact
  set_fact:
    create_users: "{{ create_users + [user.item] }}"
  loop: "{{ users_get_result.results }}"
  loop_control:
    loop_var: "user"
    label: "{{ user.item.username }}"
  when:
   - user.json.count == 0
   - user.item.state is not defined or user.item.state != "absent"

- name: Set users to update fact
  set_fact:
    update_users: "{{ update_users + [user.json.results[0] | combine(user.item) | combine({'existing_groups': user.json.results[0]['groups']}) ] }}"
  loop: "{{ users_get_result.results }}"
  loop_control:
    loop_var: "user"
    label: "{{ user.item.username }}"
  when:
   - user.json.count == 1
   - user.item.state is not defined or user.item.state != "absent"

- name: Create users
  uri:
    url: "{{ pulp_user_url }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    force_basic_auth: true
    method: POST
    status_code: 201
    body:
      username: "{{ item.username }}"
      password: "{{ item.password | default(None) }}"
      first_name: "{{ item.first_name | default(None) }}"
      last_name: "{{ item.last_name | default(None) }}"
      email: "{{ item.email | default(None) }}"
      is_staff: "{{ item.is_staff | default(None) }}"
      is_active: "{{ item.is_active | default(None) }}"
    body_format: form-urlencoded
  loop: "{{ create_users }}"
  loop_control:
    label: "{{ item.username }}"
  changed_when: true

- name: Update existing users
  uri:
    url: "{{ pulp_url }}{{ item.pulp_href }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    force_basic_auth: true
    method: PATCH
    body:
      username: "{{ item.username }}"
      password: "{{ item.password | default(None) }}"
      first_name: "{{ item.first_name | default(None) }}"
      last_name: "{{ item.last_name | default(None) }}"
      email: "{{ item.email | default(None) }}"
      is_staff: "{{ item.is_staff | default(None) }}"
      is_active: "{{ item.is_active | default(None) }}"
    body_format: form-urlencoded
  loop: "{{ update_users }}"
  loop_control:
    label: "{{ item.username }}"
  register: result
  changed_when: true

- name: Add or remove user from group(s)
  include_tasks: user_groups/add_or_remove_users.yml
  # All users that aren't state: absent are in play here
  loop: "{{ create_users + update_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

- name: Delete users
  uri:
    url: "{{ pulp_url }}{{ item.pulp_href }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    force_basic_auth: true
    method: DELETE
    status_code: 204
    body_format: form-urlencoded
  loop: "{{ remove_users }}"
  loop_control:
    label: "{{ item.username }}"
  changed_when: true
