namespace: stackhpc
name: pulp
description: >
  Roles and plugins Pulp repository server configuration
version: "0.5.4"
readme: "README.md"
authors:
  - "Piotr Parczewski"
  - "Michał Nasiadka"
  - "Mark Goddard"
dependencies:
  "pulp.squeezer": "*"
license:
  - "Apache-2.0"
tags:
  - infrastructure
  - linux
  - pulp
repository: "https://github.com/stackhpc/ansible-collection-pulp"
build_ignore:
  - settings
