---
- name: Ensure DEB publications are defined
  pulp.squeezer.deb_publication:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    repository: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ pulp_publication_deb }}"
  when: item.state == "present"
