---
- name: Ensure PyPI publications are defined
  pulp.squeezer.python_publication:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    repository: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ pulp_publication_python }}"
  when: item.state == "present"
