---
- name: Ensure RPM publications are defined
  pulp.squeezer.rpm_publication:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    repository: "{{ item.repository }}"
    state: "{{ item.state }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ pulp_publication_rpm }}"
