---

- name: Get group list
  uri:
    url: "{{ pulp_group_url }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    method: GET
    status_code: 200
    force_basic_auth: true
  no_log: true
  register: groups_list_result

- name: Set fact remove_groups
  set_fact:
    remove_groups: "{{ (remove_groups | default([])) + [item.name] }}"
  when: item.state | default('present') == 'absent'
  with_items: "{{ pulp_groups }}"

- name: Create groups
  vars:
    groupnames: "{{ groups_list_result.json.results | map(attribute='name') | list }}"
  uri:
    url: "{{ pulp_group_url }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    force_basic_auth: true
    method: POST
    status_code: 201
    body:
      name: "{{ item.name }}"
    body_format: form-urlencoded
  loop: "{{ pulp_groups | default([], true) }}"
  # no_log: true
  register: result
  when:
    - item.name not in groupnames
    - item.state | default('present') != 'absent'
  changed_when: result.status == 201

- name: Initialise hrefs
  set_fact:
    hrefs: []

- name: Set fact hrefs
  set_fact:
    hrefs: "{{ (hrefs | default([])) + [item.pulp_href] }}"
  when: item.name in (remove_groups | default([]))
  with_items: "{{ groups_list_result.json.results }}"

- name: Remove groups
  uri:
    url: "{{ pulp_url }}{{ item }}"
    user: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    force_basic_auth: true
    method: DELETE
    status_code: 204
    body_format: form-urlencoded
  loop: "{{ hrefs | default([]) }}"
  no_log: true
  register: result
  changed_when: result.status == 204
