---
- import_tasks: precheck.yml

- include_tasks: container.yml
  when: pulp_distribution_container | length > 0
  tags: container

- include_tasks: deb.yml
  tags: deb
  when: pulp_distribution_deb | length > 0

- include_tasks: rpm.yml
  tags: rpm
  when: pulp_distribution_rpm | length > 0
