---
- name: Ensure RPM distributions are defined
  pulp.squeezer.rpm_distribution:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}"
    base_path: "{{ item.base_path }}"
    publication: "{{ item.publication }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_distribution_rpm }}"
