---
- name: Setup DEB repositories
  pulp.squeezer.deb_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_deb_repos }}"

- name: Setup DEB remotes
  pulp.squeezer.deb_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}-remote"
    url: "{{ item.url }}"
    architectures: "{{ item.architectures }}"
    components: "{{ item.components }}"
    distributions: "{{ item.distributions }}"
    policy: "{{ item.policy }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_deb_repos }}"

- name: Sync DEB remotes into repositories
  pulp.squeezer.deb_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    repository: "{{ item.name }}"
    remote: "{{ item.name }}-remote"
    mirror: "{{ item.mirror | default(omit) }}"
  with_items: "{{ pulp_repository_deb_repos }}"
  when: item.state == "present"
