---
- include_tasks: deb.yml
  when: pulp_repository_deb | length > 0
  tags: deb

- include_tasks: python.yml
  when: pulp_repository_python | length > 0
  tags: python

- include_tasks: rpm.yml
  tags: rpm
  when: pulp_repository_rpm | length > 0
