---
- include_tasks: prereqs.yml
  when: >
    (pulp_repository_container_repos | length > 0) or
    (pulp_repository_deb_repos | length > 0) or
    (pulp_repository_python_repos | length > 0) or
    (pulp_repository_rpm_repos | length > 0)
  tags:
    - prereqs
    - container
    - deb
    - python
    - rpm

- include_tasks: container.yml
  when: pulp_repository_container_repos | length > 0
  tags: container

- include_tasks: deb.yml
  when: pulp_repository_deb_repos | length > 0
  tags: deb

- include_tasks: python.yml
  when: pulp_repository_python_repos | length > 0
  tags: python

- include_tasks: rpm.yml
  when: pulp_repository_rpm_repos | length > 0
  tags: rpm
