---
- name: Setup PyPI repositories
  pulp.squeezer.python_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_python_repos }}"
  loop_control:
    label: "{{ item.name }}"

- name: Setup PyPI remotes
  pulp.squeezer.python_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}-remote"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    download_concurrency: "{{ item.download_concurrency | default(omit) }}"
    excludes: "{{ item.excludes | default(omit) }}"
    includes: "{{ item.includes | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    prereleases: "{{ item.prereleases | default(omit) }}"
    proxy_url: "{{ item.proxy_url | default(omit) }}"
    proxy_username: "{{ item.proxy_username | default(omit) }}"
    proxy_password: "{{ item.proxy_password | default(omit) }}"
    remote_username: "{{ item.remote_username | default(omit) }}"
    remote_password: "{{ item.remote_password | default(omit) }}"
    tls_validation: "{{ item.tls_validation | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_python_repos }}"
  when: item.url is defined
  loop_control:
    label: "{{ item.name }}"

- name: Sync PyPI remotes into repositories
  pulp.squeezer.python_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    repository: "{{ item.name }}"
    remote: "{{ item.name }}-remote"
  with_items: "{{ pulp_repository_python_repos }}"
  when:
    - item.url is defined
    - item.state == "present"
  loop_control:
    label: "{{ item.name }}"
