---
- name: Setup PyPI repositories
  pulp.squeezer.python_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ pulp_repository_python_repos[repository_index].name }}"
    state: "{{ pulp_repository_python_repos[repository_index].state }}"
  loop: "{{ pulp_repository_python_repos | map(attribute='name') }}"
  loop_control:
    index_var: repository_index
  register: pulp_repository_python_repos_repositories
  until: "pulp_repository_python_repos_repositories is not failed"
  retries: "{{ pulp_repository_python_repos_repositories_retries }}"
  delay: 1

- name: Setup PyPI remotes
  pulp.squeezer.python_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ pulp_repository_python_repos[repository_index].name }}-remote"
    ca_cert: "{{ pulp_repository_python_repos[repository_index].ca_cert | default(omit) }}"
    client_cert: "{{ pulp_repository_python_repos[repository_index].client_cert | default(omit) }}"
    client_key: "{{ pulp_repository_python_repos[repository_index].client_key | default(omit) }}"
    download_concurrency: "{{ pulp_repository_python_repos[repository_index].download_concurrency | default(omit) }}"
    excludes: "{{ pulp_repository_python_repos[repository_index].excludes | default(omit) }}"
    includes: "{{ pulp_repository_python_repos[repository_index].includes | default(omit) }}"
    policy: "{{ pulp_repository_python_repos[repository_index].policy | default(omit) }}"
    prereleases: "{{ pulp_repository_python_repos[repository_index].prereleases | default(omit) }}"
    proxy_url: "{{ pulp_repository_python_repos[repository_index].proxy_url | default(omit) }}"
    proxy_username: "{{ pulp_repository_python_repos[repository_index].proxy_username | default(omit) }}"
    proxy_password: "{{ pulp_repository_python_repos[repository_index].proxy_password | default(omit) }}"
    remote_username: "{{ pulp_repository_python_repos[repository_index].remote_username | default(omit) }}"
    remote_password: "{{ pulp_repository_python_repos[repository_index].remote_password | default(omit) }}"
    tls_validation: "{{ pulp_repository_python_repos[repository_index].tls_validation | default(omit) }}"
    url: "{{ pulp_repository_python_repos[repository_index].url | default(omit) }}"
    state: "{{ pulp_repository_python_repos[repository_index].state }}"
  when: >
    pulp_repository_python_repos[repository_index].state == "absent" or
    pulp_repository_python_repos[repository_index].url is defined
  loop: "{{ pulp_repository_python_repos | map(attribute='name') }}"
  loop_control:
    index_var: repository_index
  register: pulp_repository_python_repos_remotes
  until: "pulp_repository_python_repos_remotes is not failed"
  retries: "{{ pulp_repository_python_repos_remotes_retries }}"
  delay: 1

- name: Sync PyPI remotes into repositories
  pulp.squeezer.python_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    repository: "{{ pulp_repository_python_repos[repository_index].name }}"
    remote: "{{ pulp_repository_python_repos[repository_index].name }}-remote"
  when:
    - pulp_repository_python_repos[repository_index].url is defined
    - pulp_repository_python_repos[repository_index].state == "present"
  loop: "{{ pulp_repository_python_repos | map(attribute='name') }}"
  loop_control:
    index_var: repository_index
  register: pulp_repository_python_repos_sync
  until: "pulp_repository_python_repos_sync is not failed"
  retries: "{{ pulp_repository_python_repos_sync_retries }}"
  delay: 1
