---
- name: Setup RPM repositories
  pulp.squeezer.rpm_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pulp_repository_rpm_repos }}"

- name: Setup RPM remotes
  pulp.squeezer.rpm_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    name: "{{ item.name }}-remote"
    url: "{{ item.url }}"
    policy: "{{ item.policy }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pulp_repository_rpm_repos }}"

- name: Sync RPM remotes into repositories
  pulp.squeezer.rpm_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    repository: "{{ item.name }}"
    remote: "{{ item.name }}-remote"
  with_items: "{{ pulp_repository_rpm_repos }}"
  when:
    pulp_sync_remotes|bool and
    item.state|default('present') == 'present'
  register: pulp_repository_rpm

- name: Ensure RPM publications are defined
  pulp.squeezer.rpm_publication:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    repository: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ pulp_repository_rpm_repos }}"
  when: pulp_distribute|bool
  register: pulp_publication_rpm

- name: Ensure RPM distributions are defined
  pulp.squeezer.rpm_distribution:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    name: "{{ result.item.name }}"
    base_path: "{{ result.item.base_path }}"
    publication: "{{ result.item.publication.pulp_href }}"
    state: "{{ result.item.state | default('present') }}"
  loop: "{{ pulp_publication_rpm.results }}"
  when:
    pulp_distribute|bool and
    result.skipped|default(false)|bool == false
  loop_control:
    loop_var: result
  register: pulp_distribution_rpm
