---
- name: Setup RPM repositories
  pulp.squeezer.rpm_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_rpm_repos }}"

- name: Setup RPM remotes
  pulp.squeezer.rpm_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ item.name }}-remote"
    ca_cert: "{{ item.ca_cert | default(omit) }}"
    client_cert: "{{ item.client_cert | default(omit) }}"
    client_key: "{{ item.client_key | default(omit) }}"
    download_concurrency: "{{ item.download_concurrency | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    proxy_url: "{{ item.proxy_url | default(omit) }}"
    proxy_username: "{{ item.proxy_username | default(omit) }}"
    proxy_password: "{{ item.proxy_password | default(omit) }}"
    remote_username: "{{ item.remote_username | default(omit) }}"
    remote_password: "{{ item.remote_password | default(omit) }}"
    tls_validation: "{{ item.tls_validation | default(omit) }}"
    url: "{{ item.url | default(omit) }}"
    state: "{{ item.state }}"
  with_items: "{{ pulp_repository_rpm_repos }}"

- name: Sync RPM remotes into repositories
  pulp.squeezer.rpm_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    repository: "{{ item.name }}"
    remote: "{{ item.name }}-remote"
    sync_policy: "{{ item.sync_policy | default(omit) }}"
  with_items: "{{  pulp_repository_rpm_repos }}"
  when: item.state == "present"
