---
- name: Add or remove content units
  stackhpc.pulp.container_contents:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    contents: "{{ pulp_container_content }}"
    concurrency: "{{ pulp_container_content_concurrency }}"
    wait: "{{ pulp_container_content_wait | bool }}"
  register: pulp_container_content_result
