---
- name: Ensure x509 cert guards exist
  pulp.squeezer.x509_cert_guard:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    validate_certs: "{{ pulp_validate_certs | bool }}"
    name: "{{ pulp_content_guard_x509_cert_guards[cert_guard_index].name }}"
    description: "{{ pulp_content_guard_x509_cert_guards[cert_guard_index].description | default(omit) }}"
    ca_certificate: "{{ pulp_content_guard_x509_cert_guards[cert_guard_index].ca_certificate | default(omit) }}"
    state: "{{ pulp_content_guard_x509_cert_guards[cert_guard_index].state }}"
  loop: "{{ pulp_content_guard_x509_cert_guards | map(attribute='name') }}"
  loop_control:
    index_var: cert_guard_index

- name: Ensure RBAC cert guards exist
  import_tasks: rbac/rbac.yml
