---
- name: Setup PyPI repositories
  python_repository:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ repositories_python }}"

- name: Setup PyPI remotes
  python_remote:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    name: "{{ item.name }}-remote"
    url: "{{ item.url }}"
    policy: "{{ item.policy }}"
    state: "{{ item.state }}"
  with_items: "{{ repositories_python }}"

- name: Sync PyPI remotes into repositories
  python_sync:
    pulp_url: "{{ pulp_url }}"
    username: "{{ pulp_username }}"
    password: "{{ pulp_password }}"
    repository: "{{ item.name }}"
    remote: "{{ item.name }}-remote"
  with_items: "{{ repositories_python }}"
  when: item.state == "present"
